@startuml

class Taller {
	- String nombre
	- ArrayList <Bicicleta> bicicletas

	cantServiciosPosibles()
	cantBicisMenosKm()
	cantBicicMenosWtts()
}

class Bicicleta {
	- String marca
	- String modelo
	- Integer cantKm
	
}

class BicicletaElectrica extends Bicicleta {
	- String marca
	- String modelo
	- Integer cantKm
	- Integer cantWtts
	
}

Taller "1.." - "..*"Bicicleta


@enduml
}